name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Pack
        run: dotnet pack --configuration Release

      - name: Publish to GitHub Packages
        run: dotnet nuget push "**/*.nupkg" `
          --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" `
          --api-key ${{ secrets.GITHUB_TOKEN }} `
          --skip-duplicate
