name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # <-- This is critical

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Authenticate with GitHub Packages
        run: dotnet nuget add source https://nuget.pkg.github.com/IndianSoftking/index.json \
          --name github \
          --username IndianSoftking \
          --password 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

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Pack
        run: dotnet pack --configuration Release

      - name: Publish
        run: dotnet nuget push **/*.nupkg --source github --skip-duplicate
