name: Publish NuGet Package

on:
  push:
    tags:
      - 'v1.0.2'
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # <-- This is critical

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Authenticate with GitHub Packages
        run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json `
          --name ISPL.NetCoreFramework `
          --username ${{ github.repository_owner }} `
          --password ${{ secrets.GITHUB_TOKEN }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Pack
        run: dotnet pack --configuration Release

      - name: Publish
        run: dotnet nuget push **/*.nupkg --source github --skip-duplicate
